# Generated by Django 5.2.6 on 2025-09-11 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="elapsed_time",
            new_name="time",
        ),
        migrations.AlterField(
            model_name="record",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
